export const CATEGORY_IDS = [
  "tecnologia",
  "ciencia",
  "historia",
  "programacion",
  "humor",
  "terror",
  "podcasts",
  "documentales",
  "economia",
  "gaming",
  "musica",
  "anime",
  "comida",
  "deportes",
] as const;

export type CategoryId = (typeof CATEGORY_IDS)[number];

export interface Category {
  id: CategoryId;
  label: string;
  emoji: string;
  /** Palabras clave usadas como query cuando el usuario no aporta términos propios. */
  seed: string[];
  /** Términos (normalizados sin acentos) que disparan esta categoría en el intent-mapper. */
  intent: string[];
}

export const CATEGORIES: Category[] = [
  {
    id: "tecnologia",
    label: "Tecnología",
    emoji: "🖥️",
    seed: ["tecnología"],
    intent: [
      "tecnologia",
      "gadgets",
      "telefono",
      "iphone",
      "android",
      "inteligencia artificial",
      "ia",
      "ai",
      "computadora",
      "ordenador",
      "laptop",
      "robot",
      "realidad virtual",
    ],
  },
  {
    id: "ciencia",
    label: "Ciencia",
    emoji: "🔬",
    seed: ["ciencia"],
    intent: [
      "ciencia",
      "cientifico",
      "cientifica",
      "universo",
      "espacio",
      "fisica",
      "quimica",
      "biologia",
      "astronomia",
      "neurociencia",
    ],
  },
  {
    id: "historia",
    label: "Historia",
    emoji: "🏛️",
    seed: ["historia"],
    intent: [
      "historia",
      "historico",
      "historica",
      "guerra",
      "imperio",
      "civilizacion",
      "medieval",
      "antiguo",
      "antigua",
      "arqueologia",
      "egipto",
      "roma",
    ],
  },
  {
    id: "programacion",
    label: "Programación",
    emoji: "💻",
    seed: ["programación"],
    intent: [
      "programacion",
      "programar",
      "codigo",
      "code",
      "developer",
      "desarrollador",
      "desarrolladora",
      "javascript",
      "python",
      "react",
      "typescript",
      "frontend",
      "backend",
      "algoritmo",
      "algoritmos",
    ],
  },
  {
    id: "humor",
    label: "Humor",
    emoji: "😂",
    seed: ["comedia"],
    intent: [
      "humor",
      "comedia",
      "gracioso",
      "graciosa",
      "divertido",
      "divertida",
      "chiste",
      "chistes",
      "risa",
      "meme",
      "memes",
    ],
  },
  {
    id: "terror",
    label: "Terror",
    emoji: "👻",
    seed: ["historias de terror"],
    intent: [
      "terror",
      "miedo",
      "susto",
      "horror",
      "paranormal",
      "fantasma",
      "fantasmas",
      "asustar",
      "espeluznante",
      "creepy",
    ],
  },
  {
    id: "podcasts",
    label: "Podcasts",
    emoji: "🎧",
    seed: ["podcasts"],
    intent: ["podcast", "podcasts"],
  },
  {
    id: "documentales",
    label: "Documentales",
    emoji: "🎬",
    seed: ["documentales"],
    intent: ["documental", "documentales", "natgeo", "nature"],
  },
  {
    id: "economia",
    label: "Economía",
    emoji: "📈",
    seed: ["economía"],
    intent: [
      "economia",
      "finanzas",
      "dinero",
      "inversion",
      "invertir",
      "negocios",
      "emprender",
      "bolsa",
      "criptomonedas",
      "ahorrar",
    ],
  },
  {
    id: "gaming",
    label: "Gaming",
    emoji: "🎮",
    seed: ["gaming"],
    intent: [
      "gaming",
      "videojuego",
      "videojuegos",
      "juegos",
      "jugar",
      "minecraft",
      "fortnite",
      "playstation",
      "xbox",
      "nintendo",
      "gta",
      "league of legends",
      "mario",
    ],
  },
  {
    id: "musica",
    label: "Música",
    emoji: "🎵",
    seed: ["música"],
    intent: [
      "musica",
      "canciones",
      "cancion",
      "playlist",
      "playlists",
      "banda",
      "bandas",
      "concierto",
      "conciertos",
    ],
  },
  {
    id: "anime",
    label: "Anime",
    emoji: "🎌",
    seed: ["anime"],
    intent: ["anime", "animes", "manga", "one piece", "naruto", "dragon ball"],
  },
  {
    id: "comida",
    label: "Comida",
    emoji: "🍔",
    seed: ["recetas fáciles"],
    intent: [
      "comida",
      "comer",
      "cocinar",
      "cocina",
      "receta",
      "recetas",
      "cena",
      "desayuno",
      "almuerzo",
      "hamburguesa",
      "pizza",
      "postre",
      "postres",
      "restaurante",
      "chef",
    ],
  },
  {
    id: "deportes",
    label: "Deportes",
    emoji: "⚽",
    seed: ["deportes"],
    intent: [
      "deportes",
      "deporte",
      "futbol",
      "baloncesto",
      "basket",
      "nba",
      "partido",
      "goles",
      "tenis",
      "f1",
      "formula 1",
      "boxeo",
      "natacion",
      "atletismo",
    ],
  },
];

export function getCategory(id: CategoryId | undefined | null): Category | undefined {
  return id ? CATEGORIES.find((c) => c.id === id) : undefined;
}

export function getCategoryLabel(id: CategoryId): string {
  return getCategory(id)?.label ?? id;
}
